### ISSUE TITLE
Suggestion:scrollspy and scroll to top

### ISSUE THREAD

**Issue by bung87** [nim-lang/website#102]
since detail page very long even haven't "detailed".

**Comment by dom96** [comment]
"detail page"?

**Comment by bung87** [comment]
sorry, my pool language.  eg .`https://nim-lang.org/docs/tables.html`

**Comment by Calinou** [comment]
A "scroll to top" button is unnecessary since you can just press the <kbd>Origin</kbd> key on your keyboard. Some mobile browsers such as iOS Safari also let you touch the title bar to scroll back to the top.

**Comment by dom96** [comment]
Also, the nim docs aren't built for mobile devices.
