### ISSUE TITLE
Reel Valley is out of business

### ISSUE THREAD

**Issue by skilchen** [nim-lang/website#104]
Please remove the stale link to [Reel Valley](https://apps.facebook.com/reelvalley?utm_source=nimsite) under [Featured Projects](https://nim-lang.org/).

**Comment by dom96** [comment]
@yglukhov any ideas what's going on?

**Comment by dom96** [comment]
I updated the link to https://onsetgame.com/ for now.

**Comment by ijks** [comment]
That link appears to be dead too now.

**Comment by dom96** [comment]
yeah... :/

We need a new project here. Any suggestions?

**Comment by timotheecour** [comment]
just ran into this, was about to submit an issue until i saw this; adding a new project would be nice, but removing dead links is a must :-)
