### ISSUE TITLE
Windows installation page doesn't say where to place PCRE and OpenSSL DLLs

### ISSUE THREAD

**Issue by kevinw** [nim-lang/website#105]
Under the "Other Dependencies" section, we have the following text:

>There are a number of other dependencies that you may need to install in order to use Nim. They include:
>
>    PCRE
>    OpenSSL
>
>Windows users can download the DLLs for these here.

It doesn't say where to put them.

**Comment by Araq** [comment]
Always next to your ``.exe`` for deployment, into ``$nim\bin`` for development. This is not specific to Nim, it's how Windows works.
