### ISSUE TITLE
And blurbs to featured projects

### ISSUE THREAD

**Issue by bambii7** [nim-lang/website#114]
These featured projects aren't very compelling at a glance. The thumbnails don't offer much. I would suggest adding icon replacements (frontend, gaming, blockchainish). And a small paragraph about each project.

<img width="1004" alt="screen shot 2018-10-04 at 5 06 10 pm" src="https://user-images.githubusercontent.com/1826459/46458065-e3f2f480-c7f7-11e8-9ced-bbab186d9754.png">

**Comment by dom96** [comment]
We lack designers who could create nice icons for these. Plus these can change, making the job even harder.

I agree with what you're saying though.

**Comment by bambii7** [comment]
<img width="1149" alt="screen shot 2018-10-08 at 9 56 06 pm" src="https://user-images.githubusercontent.com/1826459/46605550-9ce16800-cb45-11e8-9b8d-e634c8f3bb36.png">

For lack of icons could something like the attached screen shot.

I'll have a go tomorrow creating some icons, a little visual interest would be nice, alternatively there is always thenounproject with creative commons icons.

**Comment by dom96** [comment]
I like that, looks nice :)

**Comment by narimiran** [comment]
This was fixed by https://github.com/nim-lang/website/pull/116
