### ISSUE TITLE
proposal to add open graph meta tags to website

### ISSUE THREAD

**Issue by enthus1ast** [nim-lang/website#122]
open graph is a set of meta description tags for controling how a shared link on social network will display http://ogp.me/.

So if somebody would share a link of nim-lang.org on eg. facebook 
(afaik open graph was a facebook creation) the nim logo and description will be visible.

Maybe it also would have other effects, maybe better search engine ranking who knows.

It could look like this:
```html
<meta property="og:type" content="website">
<meta property="og:site_name" content="nim-lang.org">
<meta property="og:title" content="Nim programming language">
<meta property="og:description" content="Nim is a systems and applications programming language. Statically typed and compiled, it provides unparalleled performance in an elegant package.">
<meta property="og:image" content="https://nim-lang.org/assets/img/logo.png"> <!--check if eg. facebook allows svg idk. better use png -->
<meta property="og:image:secure_url" content="https://nim-lang.org/assets/img/logo.png"> <!--check if eg. facebook allows svg idk. better use png -->
<meta property="og:url" content="https://nim-lang.org">
```

**Comment by narimiran** [comment]
Fixed by https://github.com/nim-lang/website/pull/132

**Comment by dom96** [comment]
I improved this a little bit more: https://github.com/nim-lang/website/commit/b30f83849b9a118b4c33a96d95dc2f41a3febb45
