### ISSUE TITLE
Clearify statements about Pascal and Oberon

### ISSUE THREAD

**Issue by ShalokShalom** [nim-lang/website#152]
Hi :hugs: 

> 
> Oberon-inspired visibility markers
> Pascal-inspired type sections for leaner definitions

I googled and the whole Internet seems to not understand what this means. 
Link to a documentation page

**Comment by StefanSalewski** [comment]
Oberon visible marker is the * after exported symbols, and pascal section is type, var, const where the keyword can follow multiple symbols. But I agree, I can remember having seen your cited statements and I was thinking: Personally I would drop these statements, as there is nearly no benefit and wording is not really nice.

**Comment by ShalokShalom** [comment]
I see. So you think these implementations do not really serve a huge benefit? So even linking to clear explainations/examples would not help either? Thanks a lot :)

**Comment by StefanSalewski** [comment]
Implementation is fine, but these two points are not great inventions, and their use is obvious from tiny examples, so maybe not something one should mention. (The fact that you did not find the terms with google may support the idea that there is nothing special -- pascal and oberon were just the first languages using this notation. Something like use of {} for block markers or * for pointer in C -- one lang uses the notation, many other follow.)

**Comment by ShalokShalom** [comment]
Are there any other things incorporated from Oberon and Pascal?

**Comment by StefanSalewski** [comment]
Yes there are a few, for example the (sligthly modified) notion of var parameters in function parameter lists and the predefined Result variable for functions. And Nim's proc and func keywords are short versions of Procedure and Function used in Pascal.

But I think these github issues are not a discussion forum, so we should stop here.

**Comment by ShalokShalom** [comment]
Its still around the same topic. I think we all conclude, that these features are not really worth being so prominent on the homepage. Who can and will change that?

**Comment by Araq** [comment]
We will. Ping @narimiran

**Comment by ShalokShalom** [comment]
This has been solved. Thanks

**Comment by ShalokShalom** [comment]
I found another instance with this text here: 

https://nim-lang.org/features.html
