### ISSUE TITLE
Nim homepage -- oddElements example is not first class

### ISSUE THREAD

**Issue by StefanSalewski** [nim-lang/website#162]
```nim
iterator oddElements[Idx, T](a: array[Idx, T]): T =
  var i = 1
  while i < a.len:
    yield a[i]
    i += 2

for x in oddElements([10, 20, 30, 40, 50, 60]):
  echo x
```

The name oddElements is very misleading, as one would expect that it returns elements with odd VALUE, not with odd position in array. So this example is not good advertising for Nim.

**Comment by dom96** [comment]
Please submit these issues on the website repo.

**Comment by StefanSalewski** [comment]
I was not aware that there is one separate area for website, sorry.

For the oddElements iterator, I would replace that one with countup() or items() from stdlib, that are real world examples, so users learn from the beginning what really is useful.

Will close these website related issues this evening or tomorrow!

**Comment by narimiran** [comment]
> The name oddElements is very misleading

If it was called for `[1, 2, 3, 4, 5, 6]` I would consider it "very misleading". The current example has only even values (on purpose!).

**Comment by StefanSalewski** [comment]
From the name oddElements I would assume that it is not related to index position. And for a first class example I would like a name matching purpose. And an iterator skipping each second element seems not to be that often used at all, so why not take a countup() or items() from stdlib, maybe in a simplified variant?

**Comment by andreaferretti** [comment]
One could just use strings as values and remove any ambiguity on whether the name refers to odd indices or values

**Comment by narimiran** [comment]
I will write another, hopefully less ambiguous, example.
