### ISSUE TITLE
remove Google analytics from nim-lang.org

### ISSUE THREAD

**Issue by lithic** [nim-lang/website#166]

**Comment by dom96** [comment]
What's the problem with Google Analytics?

**Comment by lithic** [comment]
@dom96 we Don't want to be tracked by Google while browsing a free software's website.

**Comment by dom96** [comment]
so install uBlock or disable your JavaScript.

**Comment by lithic** [comment]
@dom96 yes, i have installed uBlock. But why you can't stop using Google analytics?

**Comment by dom96** [comment]
Because we have been using GA for years now and it works well.

**Comment by lithic** [comment]
Why you can't replace GA with It's  alternative?

**Comment by lithic** [comment]
you guys aren’t aware if the ethics of free software

**Comment by lithic** [comment]
Google analytics is a proprietary software. And you are using this on a free software's website. That's not good
