### ISSUE TITLE
Remove explicit language from tutorial page

### ISSUE THREAD

**Issue by TheSpydog** [nim-lang/website#169]
Hi all! I teach programming lessons for kids, and given the elegant simplicity of Nim, I'd love to find a way to integrate it into my curriculum. But before I can feel comfortable doing that, I have a somewhat awkward request:

Would it be possible to censor the reference to Brainfuck in the Learn Nim > Community Resources page? (Maybe to "Brainf***" or something similar?) I know it sounds petty, but I'm concerned that my students (or perhaps more importantly, the parents of my students) might look up the website to find more resources and feel uncomfortable with the explicit language. Where I live in the USA, this could be a big deal for some people, and I really don't want to upset anyone.

(I realize that some folks may click the link anyway, but at that point they're on an external website that's not directly managed by Nim, so they've voluntarily taken the risk of seeing whatever lies beyond.)

**Comment by dom96** [comment]
That's definitely a fair request, fixed in https://github.com/nim-lang/website/commit/358b30beb86ff7d33362392ab806180a086aad19. :)
