### ISSUE TITLE
Can't sign up to the forum

### ISSUE THREAD

**Issue by foldl** [nim-lang/website#175]
Error message: "Unknown error occurred."

Tested on Edge and Firefox.

**Comment by dom96** [comment]
Please try again.

**Comment by foldl** [comment]
The same error again.

**Comment by dom96** [comment]
Please email the details you are trying to register with to support[at]nim-lang.org and I'll see if I can reproduce.

**Comment by foldl** [comment]
I have sent an Email. Please have a check.

**Comment by foldl** [comment]
OK after my network can access reCAPTCHA.
