### ISSUE TITLE
Add a Playgroud

### ISSUE THREAD

**Issue by Firefell** [nim-lang/website#179]
Hello,

A Playground like [nim.ide.judge0.com](nim.ide.judge0.com) in the website can be a good idea.

In the future, add a interactive tutorial to it.

Thanks

**Comment by narimiran** [comment]
There's an official playground, available at https://play.nim-lang.org/

**Comment by trustable-code** [comment]
Maybe a link to https://nim.ide.judge0.com should be added to https://nim-lang.org/learn.html too?

**Comment by narimiran** [comment]
> Maybe a link to https://nim.ide.judge0.com should be added to https://nim-lang.org/learn.html too?

Done.

**Comment by Firefell** [comment]
> There's an official playground, available at https://play.nim-lang.org/

I'm sorry I don't see it, a link in the first page between **Learn** and **Documentation** is maybe better.

I prefer Judge0 interface, it's more like a desktop editor. In **play.nim-lang**, it should be good to add a menu to try several examples. Maybe change **play.nim-lang** by **nim.ide.judge0**. Why not ?
