### ISSUE TITLE
[UX] Dark Mode isn't saved for next page/session/load

### ISSUE THREAD

**Issue by hugosenari** [nim-lang/website#204]
**How to reproduce:**
- Open some docs page
- Set dark mode on
- Reload de page

**Current Behavior:**
* Every time I open docs, dark mode is off

**Expected Behavior:**
* Every time I open docs, dark mode is at last page/visit/session state (on or off)

**Comment by trustable-code** [comment]
I think it would be good to save it per localStorage.

**Comment by KingDarBoja** [comment]
AFAIK this can be done with Karax [localstorage](https://github.com/pragmagic/karax/blob/master/karax/localstorage.nim) procedures but not sure.

**Comment by trustable-code** [comment]
The selected theme is already saved per localStorage, see https://github.com/nim-lang/Nim/blob/devel/config/nimdoc.cfg#L233 .
As I understand the code, the selected theme is restored from localStorage **only** if `window.matchMedia` does not match dark or light. Maybe this needs to be removed?

**Comment by KingDarBoja** [comment]
@trustable-code just tested it and it does work, not sure why that `window.matchMedia` is doing but removing it is the key.

**Comment by hugosenari** [comment]
fixed
