### ISSUE TITLE
Improve Nim's branding on Github

### ISSUE THREAD

**Issue by alaviss** [nim-lang/website#210]
This shouldn't take too much effort to fix (nor is too important), but I'm opening an issue anyway to remind us to get this sorted out:

This is how our Github org looks like atm:

![image](https://user-images.githubusercontent.com/4961280/91495416-0b4e8100-e8aa-11ea-868c-5ad94c0020d5.png)

It just looks unprofessional. Here's nim-lang-cn org page for comparison:

![image](https://user-images.githubusercontent.com/4961280/91495548-38029880-e8aa-11ea-8f9b-7293bcbfa414.png)

Just having the name, some descriptions, a few links and it will look much much better.

**Comment by dom96** [comment]
Agreed. Wanna brainstorm a description?

**Comment by dom96** [comment]
Boom 
![image](https://user-images.githubusercontent.com/246651/91496639-608f9000-e8b4-11ea-8839-2d344ce93931.png)

**Comment by alaviss** [comment]
> Agreed. Wanna brainstorm a description?

Maybe: "Nim is a systems programming language with a focus on efficiency, expressiveness, and elegance."? It doesn't say much about Nim's uniqueness but I don't think short summaries should be concerned with that.

Also can you change "nim-lang" to "The Nim Programming Language"?

**Comment by dom96** [comment]
Okay, I added those things.

**Comment by xflywind** [comment]
I think this issue can be closed
![image](https://user-images.githubusercontent.com/43030857/93728345-26cf5200-fbf2-11ea-99b6-5d3994e5c4dd.png)
