### ISSUE TITLE
32Bit Downloads

### ISSUE THREAD

**Issue by juancarlospaco** [nim-lang/website#212]
I have some experience with new users on Nim, related to some Nim-powered open source,
sometimes noobs install 32Bit Nim on 64Bit OS, no new 32Bit hardware for PC been built since the 90's or 2000's,
on the Nim website the 2 versions are similar visually and no other explanation given.

Some people come from scripting interpreted languages, and been using 32Bit out of habit until today,
when your code runs inside a virtual machine theres no difference, but for native machine code it does.

Maybe the 32Bit download can be smaller or less significant visually, and add a tiny comment or tooltip
"Nowadays all PC are 64Bit hardware, theres no modern 32Bit PC, probably you should use 64Bit Nim" or similar.

![temp](https://user-images.githubusercontent.com/1189414/92008789-f8aad080-ed1d-11ea-9e9b-9f227c1f70d8.png)

:)

**Comment by Araq** [comment]
Good idea. Ping @narimiran

**Comment by juancarlospaco** [comment]
Thanks @narimiran
