### ISSUE TITLE
Suggestion: use Elm to simplify homepage development

### ISSUE THREAD

**Issue by unquietwiki** [nim-lang/website#217]
https://elm-lang.org/ might be useful to replace a lot of the HTML code; http://builtwithelm.co/ has some examples.

It might also open up an avenue to explore using Nim meta-programming for Elm?

**Comment by trustable-code** [comment]
> Elm is a functional language that compiles to JavaScript.

As this is the Nim project, we prefer to use Nim :)
I don't understand what you mean by replacing HTML code. Do you mean server-side or client-side generation?

**Comment by Calinou** [comment]
I think the current static HTML is doing its job fine. It's the fastest and most secure option you can have :slightly_smiling_face:

**Comment by Araq** [comment]
Our website used to use a website generator written in Nim and will eventually return to that. No need for Elm or Hugo or ...

**Comment by unquietwiki** [comment]
@trustable-code @Calinou @Araq That's fair. I wanted to see if it was a chance to practice on both, and make use of features in one, the other may not have. I also realize that Nim metaprogramming handles HTML just fine.

**Comment by Yardanico** [comment]
> @trustable-code @Calinou @Araq That's fair. I wanted to see if it was a chance to practice on both, and make use of features in one, the other may not have. I also realize that Nim metaprogramming handles HTML just fine.

Maybe you don't know, but Nim also has a JS backend for writing website frontends :)
