### ISSUE TITLE
Listing of older Nim versions

### ISSUE THREAD

**Issue by dom96** [nim-lang/website#225]
We need a link to older versions of Nim on the download page, at the very least the latest 1.0.x version should be linked. But ideally we should have a nice page listing all the previous versions.

**Comment by KingDarBoja** [comment]
I think it should be a list with two columns, one for the version and another for release date. If that's the case, willing to do it :)

**Comment by ee7** [comment]
> I think it should be a list with two columns, one for the version and another for release date.

Just in case it's useful to anyone: to get a list of dates/tags from the Nim repo you can do something like:

```
git tag --list --sort=-creatordate --format='%(creatordate:short) - %(refname:short)'
```

Expand the below for some tables.

<details><summary>Sorted by date, then version</summary>

| Date       | Version |
| :--------- | ------- |
| 2020-10-16 | 1.4.0   |
| 2020-10-16 | 1.2.8   |
| 2020-10-16 | 1.0.10  |
| 2020-07-30 | 1.0.8   |
| 2020-07-30 | 1.2.6   |
| 2020-06-27 | 1.2.4   |
| 2020-06-17 | 1.2.2   |
| 2020-04-03 | 1.2.0   |
| 2020-01-24 | 1.0.6   |
| 2019-11-27 | 1.0.4   |
| 2019-10-23 | 1.0.2   |
| 2019-09-23 | 1.0.0   |
| 2019-07-16 | 0.20.2  |
| 2019-06-06 | 0.20.0  |
| 2019-05-10 | 0.19.6  |
| 2019-01-31 | 0.19.4  |
| 2018-12-31 | 0.19.2  |
| 2018-09-26 | 0.19.0  |
| 2018-03-01 | 0.18.0  |
| 2017-09-07 | 0.17.2  |
| 2017-05-17 | 0.17.0  |
| 2017-01-08 | 0.16.0  |
| 2016-10-23 | 0.15.2  |
| 2016-10-01 | 0.15.0  |
| 2016-06-11 | 0.14.2  |
| 2016-06-07 | 0.14.0  |
| 2016-01-18 | 0.13.0  |
| 2015-10-27 | 0.12.0  |
| 2015-05-04 | 0.11.2  |
| 2015-04-30 | 0.11.0  |
| 2014-12-29 | 0.10.2  |
| 2014-10-19 | 0.9.6   |
| 2014-04-21 | 0.9.4   |
| 2013-05-20 | 0.9.2   |
| 2012-09-23 | 0.9.0   |
| 2012-02-09 | 0.8.14  |

</details>

<details><summary>Sorted by version</summary>

| Version |       Date |
| ------- | ---------- |
|   1.4.0 | 2020-10-16 |
| | |
|   1.2.8 | 2020-10-16 |
|   1.2.6 | 2020-07-30 |
|   1.2.4 | 2020-06-27 |
|   1.2.2 | 2020-06-17 |
|   1.2.0 | 2020-04-03 |
| | |
|  1.0.10 | 2020-10-16 |
|   1.0.8 | 2020-07-30 |
|   1.0.6 | 2020-01-24 |
|   1.0.4 | 2019-11-27 |
|   1.0.2 | 2019-10-23 |
|   1.0.0 | 2019-09-23 |
| | |
|  0.20.2 | 2019-07-16 |
|  0.20.0 | 2019-06-06 |
|  0.19.6 | 2019-05-10 |
|  0.19.4 | 2019-01-31 |
|  0.19.2 | 2018-12-31 |
|  0.19.0 | 2018-09-26 |
|  0.18.0 | 2018-03-01 |
|  0.17.2 | 2017-09-07 |
|  0.17.0 | 2017-05-17 |
|  0.16.0 | 2017-01-08 |
|  0.15.2 | 2016-10-23 |
|  0.15.0 | 2016-10-01 |
|  0.14.2 | 2016-06-11 |
|  0.14.0 | 2016-06-07 |
|  0.13.0 | 2016-01-18 |
|  0.12.0 | 2015-10-27 |
|  0.11.2 | 2015-05-04 |
|  0.11.0 | 2015-04-30 |
|  0.10.2 | 2014-12-29 |
|   0.9.6 | 2014-10-19 |
|   0.9.4 | 2014-04-21 |
|   0.9.2 | 2013-05-20 |
|   0.9.0 | 2012-09-23 |
|  0.8.14 | 2012-02-09 |

</details>

**Comment by narimiran** [comment]
> If that's the case, willing to do it

Thanks, but I'm already working on it. PR should be ready by the end of the day.
