### ISSUE TITLE
Weird styling for the post authors in the blog

### ISSUE THREAD

**Issue by Yardanico** [nim-lang/website#231]
Screenshots say everything:
![image](https://user-images.githubusercontent.com/21169548/96044380-01440a00-0e79-11eb-931c-c647a1f001ee.png)
![image](https://user-images.githubusercontent.com/21169548/96044413-0f922600-0e79-11eb-9444-e42be0e62b16.png)

**Comment by Yardanico** [comment]
Seems to come from https://github.com/nim-lang/website/blob/master/jekyll/assets/css/main.scss#L184, removing `  text-align: justify;` fixes this but also changes the excerpt of the blog posts.

**Comment by narimiran** [comment]
> also changes the excerpt of the blog posts.

IMO, it is ok if excerpt is left-aligned.

**Comment by Yardanico** [comment]
@narimiran I think I've found a better solution
