### ISSUE TITLE
Improve readability of text and code blocks in blog posts

### ISSUE THREAD

**Issue by ee7** [nim-lang/website#260]
https://github.com/nim-lang/website/pull/259 is a huge improvement, but I've always thought that there's something else about text and code blocks in Nim blog posts that decreases readability.

As an example, compare:
- https://nim-lang.org/blog/2020/10/16/version-140-released.html
- https://github.com/nim-lang/website/blob/master/jekyll/_posts/2020-10-16-version-140-released.md#gc-orc

I find it much easier to read on GitHub. Do others agree?

Some suggestions:
1. Make headers at the level of "Known incompatibilities and gotchas" and "Deepcopy" more obvious - it's currently much harder to distinguish sections than on GitHub.
2. Add horizontal padding inside inline code blocks, and have a bigger difference between the font faces. The code blocks in the bottom image below tend to blend into the regular text.

![1](https://user-images.githubusercontent.com/45465154/106517992-865f3780-64d9-11eb-9bcf-603760bbdc5f.png)
![2](https://user-images.githubusercontent.com/45465154/106517998-8828fb00-64d9-11eb-9e68-fbf7029be6a4.png)

Maybe people have some other suggestions.

Somewhat related: https://github.com/nim-lang/website/issues/202

**Comment by narimiran** [comment]
> Make headers at the level of "Known incompatibilities and gotchas" and "Deepcopy" more obvious - it's currently much harder to distinguish sections than on GitHub.

Agreed. I'll work on this.
