### ISSUE TITLE
Website has broken/overlapped text rendering on iOS

### ISSUE THREAD

**Issue by moigagoo** [nim-lang/website#277]
<img width="375" alt="Documentation - Nim Programming Language" src="https://user-images.githubusercontent.com/1045340/114731863-20055980-9d53-11eb-9d15-1e484d410f90.png">

**Comment by moigagoo** [comment]
Screenshot taken on iPhone 7.

**Comment by narimiran** [comment]
Ouch!!

Thanks for the report, I'll deal with this.
