### ISSUE TITLE
Update the Discord logo to the latest version

### ISSUE THREAD

**Issue by Panquesito7** [nim-lang/website#285]
The Discord logo recently has changed. We should update it to the new one (check Discord's [branding page](https://discord.com/branding)).

**Comment by Yardanico** [comment]
This is not really up to us, the website simply uses icons from Font Awesome

**Comment by Panquesito7** [comment]
> This is not really up to us, the website simply uses icons from Font Awesome

You can add the SVG directly, that would work. 🙂

**Comment by dom96** [comment]
PRs welcome :)

**Comment by Panquesito7** [comment]
Working on it. Thanks.
