### ISSUE TITLE
Can't Sign Up for NIM Forum

### ISSUE THREAD

**Issue by Red-Sage** [nim-lang/website#327]
I'm sorry to post this here (if is the wrong place) but I can't figure out any other way to get this message out. I have been trying to sign up for the forum at [forum.nimlang-org](https://forum.nim-lang.org/) but I never receive a confirmation email. I have tried several different email addresses and they all fail (that is to say, I never receive the confirmation email). I have tried the basic troubleshooting like checking junk and corporate spam filters. Maybe it's just me or maybe the site is not working. I thought someone might want to confirm.

On a related note, can I ask for NIM help here?

**Comment by dom96** [comment]
what's your nickname, we can activate your account for you

**Comment by Red-Sage** [comment]
I think it's 'casey314'...I created and deleted my account and I think that is the one that is still active.

**Comment by dom96** [comment]
if you deleted it I can't activate it... :/

**Comment by Red-Sage** [comment]
Hey @dom96 , I'm sorry I thought that account was still active. I just tried this again today with the nickname RedSage. If your not too annoyed would you activate that account? Thanks!

**Comment by Yardanico** [comment]
@Red-Sage activated your account

**Comment by ringabout** [comment]
It seems to have been solved.
