### ISSUE TITLE
Enable channels and threads in "Nim playground"

### ISSUE THREAD

**Issue by hholst80** [nim-lang/website#328]
I think it would be a good idea to enable threads and channels in the playground site. These features are what makes Nim interesting.

**Comment by Yardanico** [comment]
It wouldn't be a good idea to enable them *by default*, but having a checkbox would be okay. The reason for not enabling the by default is that some code can be rejected with the compiler with `--threads:on` if it worked without that.

And channels don't need to be enabled by themselves, they're a part of threads.

**Comment by Yardanico** [comment]
Also, this should be opened in a separate repository - https://github.com/PMunch/nim-playground. Please close your issue here and open it there

**Comment by hholst80** [comment]
Superseded by https://github.com/PMunch/nim-playground/issues/13
