### ISSUE TITLE
Also, this should be opened in a separate repository - https://github.com/PMunch/nim-playground. Please close your issue here and open it there

### ISSUE THREAD

**Issue by hholst80** [nim-lang/website#329]
Also, this should be opened in a separate repository - https://github.com/PMunch/nim-playground. Please close your issue here and open it there

_Originally posted by @Yardanico in https://github.com/nim-lang/website/issues/328#issuecomment-1079202737_

**Comment by Yardanico** [comment]
??? why did you open another issue in the same repo instead of opening a new one in a different one?

**Comment by hholst80** [comment]
Tried to use the GitHub shortcut it did not work, but apparently it did do something. 🙃 
![image](https://user-images.githubusercontent.com/6200749/160209257-3a7c4e93-9795-415b-af34-49eb18343e4c.png)
