### ISSUE TITLE
[IDEA] Add a license to the repository

### ISSUE THREAD

**Issue by Panquesito7** [nim-lang/website#331]
**Description**

We should add a license to this repository. This way, people will know what and what not they can do with this repository, permissions, notices, etc.. I suggest adding the [**MIT license**](https://mit-license.org).

**Additional Context**    

https://www.freecodecamp.org/news/how-open-source-licenses-work-and-how-to-add-them-to-your-projects-34310c3cf94/

**Comment by Yardanico** [comment]
![image](https://user-images.githubusercontent.com/21169548/162461008-817058d6-90f4-42ca-9981-c1402e22ff23.png)

**Comment by dom96** [comment]
Feel free to make a PR to add it, but for now the license is in the readme.

**Comment by Panquesito7** [comment]
Question: so the design is licensed under CC BY-SA 3.0, and the code? 🤔

**Comment by pietroppeter** [comment]
Actually from the readme I would say that, apart from the design m, everything else (unless explicitly mentioned, but I do not see other mentions) is under Creative Commons (which includes the code).

**Comment by Panquesito7** [comment]
Not a very good idea to use CC licenses for code, but well.
I guess I'll create a PR to add the LICENSE file with that.

Thanks.

**Comment by pietroppeter** [comment]
Mmh, indeed we usually use MIT for code. We probably could change it?
