### ISSUE TITLE
Get Site Buildable For N00bs.

### ISSUE THREAD

**Issue by nodanaonlyzuul** [nim-lang/website#37]
Heyo.

Firstly - thanks to the maintainers of the site and the language itself.
nim is clearly a labor of love - and I'm excited to learn more about it.

Following the directions in `master`'s README I run...:

```
$ jekyll server
Configuration file: none
Configuration file: none
     Build Warning: Layout 'page' requested in jekyll/blog.html does not exist.
     Build Warning: Layout 'page' requested in jekyll/community.md does not exist.
     Build Warning: Layout 'page' requested in jekyll/documentation.html does not exist.
     Build Warning: Layout 'default' requested in jekyll/donate.md does not exist.
     Build Warning: Layout 'page' requested in jekyll/examples.html does not exist.
     Build Warning: Layout 'page' requested in jekyll/faq.md does not exist.
     Build Warning: Layout 'default' requested in jekyll/features.html does not exist.
     Build Warning: Layout 'default' requested in jekyll/index.html does not exist.
     Build Warning: Layout 'default' requested in jekyll/install.md does not exist.
     Build Warning: Layout 'page' requested in jekyll/install_unix.md does not exist.
     Build Warning: Layout 'page' requested in jekyll/install_windows.md does not exist.
  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'jekyll/assets/css/main.scss':
                    File to import not found or unreadable: variables. on line 1
```

This is on ruby 2.3.0 0, jekyll 3.4.3.

I'm not sure where to go from here but a few humble suggestions might be...

1.  Committing a `.ruby-version` and `.ruby-gemset` file for folks who use rvm or rbenv.
1.  Adding a Gemfile to lock down to a specific version of Jekyll.

**Comment by dom96** [comment]
Did you ``cd`` into ``jekyll``?

**Comment by nodanaonlyzuul** [comment]
Doh! @dom96 - you're totally right - I hadn't. My mistake. Thanks.

It's up to you if you'd like to close this issue. 
I _do_ think in the long run it would be good to add the `Gemfile` and `.ruby-*` files. 

Thanks for your time - I really appreciate it.

**Comment by dom96** [comment]
PRs welcome :)
