### ISSUE TITLE
Match OS & Dark theme for /docs seems to have been broken recently

### ISSUE THREAD

**Issue by ITwrx** [nim-lang/website#375]
I want to say a few weeks ago i noticed that the Match OS and Dark themes no longer worked for `https://nim-lang.org/docs/*`. 

tried firefox 115.0.2 and chromium 115.0.5790.102 (fedora 37)

thanks

**Comment by Araq** [comment]
It's a file caching issue. Some intermediate server caches .css files for monts and we don't know how to stop it.

**Comment by ITwrx** [comment]
oh, ok. I'll leave it for you to decide if you want this issue left open for tracking or not.

thanks

**Comment by ringabout** [comment]
will be fixed by https://github.com/nim-lang/Nim/pull/22378
