### ISSUE TITLE
Add Offline Documentation Option

### ISSUE THREAD

**Issue by Raxelgrande** [nim-lang/website#386]
Currently, if you go to https://nim-lang.org/docs/lib.html you will find a lot of documentation, but there's a problem. 
You can't download the contents for offline use. 

This is especially troublesome for developing areas of the planet with very limited internet access, travellers who don't have a connection availabe or just for people that want an offline option. 
It's likely there are more sites inside Nim that could benefit from an offline option as well. 

A good solution would be to provide the pages in PDF form, like how Python does.

**Comment by Araq** [comment]
Nah.
