### ISSUE TITLE
Broken download links for windows

### ISSUE THREAD

**Issue by dragsbruh** [nim-lang/website#390]
The download links for 32 bit and 64 bit windows executable is broken, the 64 bit doesnt even show up.

![image](https://github.com/nim-lang/website/assets/77605763/35b94a46-8c70-4da7-96f5-ad9182276936)

**Comment by Yardanico** [comment]
![image](https://github.com/nim-lang/website/assets/21169548/8df81aad-97df-4ed2-8a92-8653c1dfc78d)
Shows up fine here, just to check - are you sure it's not your antivirus acting up?

**Comment by dragsbruh** [comment]
> Shows up fine here, just to check - are you sure it's not your antivirus acting up?

Yeah the issue is with brave, opera works fine.
