### ISSUE TITLE
Article submission

### ISSUE THREAD

**Issue by johnnovak** [nim-lang/website#41]
Hi guys, this is my guest author article submission. Feel free to post it on the nim-lang front page if you think it's worthy enough :)

http://blog.johnnovak.net/2017/04/22/nim-performance-tuning-for-the-uninitiated/

**Comment by dom96** [comment]
Nice! Think you could create a PR?

**Comment by johnnovak** [comment]
Actually, now I'm slightly confused, because I thought there would be just a short post on the Nim blog with a link to my article... But then I realised this offer was more about writing guest posts that would be actually published on the Nim blog...

So is just a short paragraph with a link okay? If not, that's cool too, I just don't have time to reformat the whole article for the Nim blog.

**Comment by dom96** [comment]
Sorry, I would rather have full blog posts on nim-lang.org rather than just links. But we should also get http://planet.nim-lang.org working soon too, which would be nice.

**Comment by dom96** [comment]
In any case, I'll close this for now.

**Comment by johnnovak** [comment]
Cool, no prob :)
