### ISSUE TITLE
A provisional "wiki" page?

### ISSUE THREAD

**Issue by wizzardx** [nim-lang/website#53]
Hi!

I heard that the Nim community had a nediawiki some years back, but that it was ocerrun with spam bots so shut down.

I'd like to revive that idea; eg somewhere wiki-like. Somewhere really informal; unlike the main site. Eg, as a kind of counterpart to IRC and Forum areas, but less susceptible to being overrun with spam bots.

And then a bunch of these tickets could also be closed by making random wiki link entries.

If not Mediawiki, then what else might work?

Could I just do a git pull against the website code, in the community section, and then to add wiki contents; people do a lot of pull requests against there?

If that gets a bit out of hand then maybe all that could be done in a a separate git repo. (?)

**Comment by Araq** [comment]
What's wrong with the wiki pages that github offers?

**Comment by wizzardx** [comment]
Last core dev I chatted to indicated that there was no wiki these days. I'll assume your reply here is a semi-official endorsement. Thanks for the reply!
