### ISSUE TITLE
Add Favicon

### ISSUE THREAD

**Issue by wizzardx** [nim-lang/website#55]
So that things are a bit prettier, eg if you have a lot of different web browser tabs open on different sites. At the moment the Nim website and forum stand out a bit as having blank icons :-)

**Comment by dom96** [comment]
The website has a favicon

**Comment by wizzardx** [comment]
Thanks, my bad, I see that. I think I meant the forum, rather than the website:

https://forum.nim-lang.org/

I'll go post that against the nimforum github repo. Closing this ticket, thanks!
