### ISSUE TITLE
Fix Nimble Logo

### ISSUE THREAD

**Issue by malyutinegor** [nim-lang/website#58]
I not sure to create a pull request so I'm created an issue.
There are a small gaps between polygons, but with my perfectionism and budget monitor they are very notable:
![](https://transfer.sh/OY9SH/nimbleg.svg)
I tried to fix it. Here's what I got:
![](https://transfer.sh/nH7TZ/nimble.svg)

**Comment by dom96** [comment]
Thank you, can you create a PR to replace it [here](https://github.com/nim-lang/website/blob/master/jekyll/assets/img/nimble.svg)? :)
