### ISSUE TITLE
Awesome Nim feature list

### ISSUE THREAD

**Issue by dom96** [nim-lang/website#6]
The following is a list of awesome features that should be advertised on the front page.

* Sub-milisecond GC pauses (This is being introduced into Golang at the minute, https://twitter.com/brianhatfield/status/804355831080751104, but is something we've had for a while): http://forum.nim-lang.org/t/2646
  * https://medium.com/@octskyward/modern-garbage-collection-911ef4f8bd8e#.og8w1s46v

**Comment by andreaferretti** [comment]
Also Nimble and its ecosystem should be mentioned somewhere

**Comment by dom96** [comment]
Well, we mentioned them both to a certain extent :)
