### ISSUE TITLE
wrong String in Slices tutorial

### ISSUE THREAD

**Issue by njittam** [nim-lang/website#63]
See https://nim-lang.org/docs/tut1.html#advanced-types-slices

b is initialized as `b = "Slices are useless."`
however in a few lines later it says: `echo b # --> 'Slices are useful.'`

it seems to be that the line where b is initialized is wrong. it should be 
b is initialized as `b = "Slices are useful."`

**Comment by dom96** [comment]
You can fix that in the Nim repo: https://github.com/nim-lang/Nim/blob/devel/doc/tut1.rst

**Comment by narimiran** [comment]
As already said in that PR, the example is correct.
