### ISSUE TITLE
Japanese Tutorial

### ISSUE THREAD

**Issue by kekeho** [nim-lang/website#64]
Hi, I'm Japanese.
I wanna translate [tutorial](https://nim-lang.org/docs/tut1.html) to Japanese.
So, What should I do first?

**Comment by dom96** [comment]
The relevant file is here: https://github.com/nim-lang/Nim/blob/devel/doc/tut1.rst

Translate it, save it as ``tut1.jp.rst`` and make a PR :)

**Comment by kekeho** [comment]
OK, thx 😄
