### ISSUE TITLE
List of inspirations

### ISSUE THREAD

**Issue by dom96** [nim-lang/website#7]
This isn't really an issue, more a reference of programming language websites that we should take some inspiration from.

- http://racket-lang.org/ - https://news.ycombinator.com/item?id=13242590

**Comment by andreaferretti** [comment]
This is pretty good http://eta-lang.org/

Racket does not look like a programming language site at all, more like a charting library

**Comment by dom96** [comment]
A non-language website that is very nice https://rethinkdb.com/

**Comment by dom96** [comment]
This appears to be a very common way to present a bunch of information in a stylish way, another example: https://ghost.org/journalism/

**Comment by dom96** [comment]
Another site: https://sandstorm.io

**Comment by narimiran** [comment]
> This isn't really an issue

Closing, so we can have higher SNR when browsing through the open issues.

This list can be, of course, further updated even if this is closed.
