### ISSUE TITLE
/docs/apis.html gives a 404 response, but is hyperlinked on /docs/lib.html

### ISSUE THREAD

**Issue by SteveAdams** [nim-lang/website#71]
[https://nim-lang.org/docs/lib.html](https://nim-lang.org/docs/lib.html)

Click on the link to the document about the standard lib's API design (Xpath is `//*[@id="content"]/p[4]/a`) and you will get a 404.

I was going to create a PR for this issue, but I'm not sure where the docs are hosted. Happy to help out if I can.

**Comment by dom96** [comment]
This is Nim issue rather than the website's issue. Maybe recreate this in that Nim repo.

**Comment by SteveAdams** [comment]
Ah, thanks! I don't immediately see where it is in there, but I'll find it.
