### ISSUE TITLE
nimblepkglist.js on library page fails to load with 404

### ISSUE THREAD

**Issue by adelq** [nim-lang/website#74]
The Nim libraries documentation page, https://nim-lang.org/docs/lib.html#nimble, attempts to load `nimblepkglist.js`. However, this leads to a 404 HTTP error code (https://nim-lang.org/docs/nimblepkglist.js), and so the page displays an error that "If you are reading this you are missing nimblepkglist.js or have javascript disabled in your browser.", and the JS console displays "Uncaught ReferenceError: gotPackageList is not defined".

I couldn't find a better place to post this, I couldn't find the source for nimblepkglist.js in the Nim repositories I checked.

**Comment by dom96** [comment]
https://github.com/nim-lang/Nim/blob/devel/web/nimblepkglist.nim :)

I think we will simply link to https://nimble.directory in the future.

**Comment by dom96** [comment]
Fixed now.
