### ISSUE TITLE
A list of things that are not official but might be interesting to list somewhere

### ISSUE THREAD

**Issue by andreaferretti** [nim-lang/website#9]
or maybe make them official! :-)

https://github.com/moigagoo/nimage
http://nimble-explorer.com/
https://glot.io/new/nim

**Comment by moigagoo** [comment]
I should definitely rename nimage to "The Nim Docker Images." "Nimage" is super non-descriptive. Also, I believe nimage is an existing project that has something to do with images.

**Comment by timeyyy** [comment]
https://github.com/VPashkov/awesome-nim

**Comment by andreaferretti** [comment]
http://nimism.co/

**Comment by narimiran** [comment]
> https://github.com/VPashkov/awesome-nim

I'm taking this as a solution for this problem. That list should be populated (by the community), and I'll see if we can have an official link to it somewhere.

**Comment by andreaferretti** [comment]
That list is not nearly as useful as linking a few selected things on the official website

**Comment by andreaferretti** [comment]
Closing since all of these are mentioned in the new website
