### ISSUE TITLE
[feature] access docs for `devel` branch

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/website#98]
something like: https://dlang.org/phobos-prerelease/std_algorithm.html (which even has a way to select the tag/branch eg 2.080 instead of `master`, although at least allowing to serve docs from tip of `devel` branch, say updated after every PR would be already a big improvement)

## EDIT: this is now implemented as of https://github.com/nim-lang/Nim/pull/8992
* [[RFC] regarding committing docs and auto-updating documentation website · Issue #25 · citycide/glob](https://github.com/citycide/glob/issues/25)
* https://github.com/kaushalmodi/nim-nightly-docs
* Visit https://nim-lang.github.io/Nim/ for the latest docs built from the Nim devel branch.

**Comment by timotheecour** [comment]
=> https://github.com/nim-lang/Nim/pull/8423 after this PR, we can work around this by building docs locally (more flexible since allows building docs for arbitrary commits/branches, but maybe still worth publishing docs for `devel` branch regardless for ease of use for ppl who don't want to build docs locally yet see latest devel docs

**Comment by timotheecour** [comment]
I believe git hooks could be used for that purpose, ie update docs whenever `devel` is updated with a new commit, see https://www.digitalocean.com/community/tutorials/how-to-use-git-hooks-to-automate-development-and-deployment-tasks

**Comment by awr1** [comment]
+1 from me. I much prefer to use the online docs more than the locally generated ones, and it would be nice to have the ones from `devel` up there.

**Comment by timotheecour** [comment]
thanks @kaushalmodi for implementing this! closing
